version: '3'
services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./website:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    container_name: web

  api:
    build: ./api
    environment:
      - MONGODB_URI=mongodb://db:27017/myapp
    depends_on:
      - db
    container_name: api

  db:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    container_name: db

volumes:
  mongodb_data: 